name: PR Scan

on:
  workflow_dispatch:  
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened

concurrency:
  group: pr-scan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Linter Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      issues: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super linter
        uses: super-linter/super-linter/slim@v8.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SAVE_SUPER_LINTER_OUTPUT: true
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: true
          LINTERLINTER_RULES_PATH: .
          PYTHON_FLAKE8_CONFIG_FILE: .flake8
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          PYTHON_ISORT_CONFIG_FILE: pyproject.toml
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_PYTHON_ISORT: true
          VALIDATE_ALL_CODEBASE: false
