name: PR Scan

on:
  workflow_dispatch:  
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened

concurrency:
  group: pr-scan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Linter Scan
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read
      issues: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Super linter
        uses: super-linter/super-linter/slim@v8.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SAVE_SUPER_LINTER_OUTPUT: true
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: true
          LINTER_RULES_PATH: .
          PYTHON_FLAKE8_CONFIG_FILE: .flake8
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          PYTHON_ISORT_CONFIG_FILE: pyproject.toml
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_PYTHON_ISORT: true
          VALIDATE_MARKDOWN: true
          VALIDATE_MARKDOWN_PRETTIER: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: true
          VALIDATE_ALL_CODEBASE: false
          FIX_PYTHON_BLACK: true
          FIX_PYTHON_ISORT: true
          FIX_MARKDOWN: true
          FIX_MARKDOWN_PRETTIER: true

      - name: Commit and push linting fixes
        if: >
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
